attendance/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from . import views 

urlpatterns = [
    url(r'^$', views.home_page, name='home'),
    url(r'^coach/dashboard/$', views.coach_dashboard, name='coach_dashboard'),
    url(r'^coach/(?P<coach_id>\d+)/roster/(?P<class_id>\d+)/$', views.class_roster, name='class_roster'),
    url(r'^coach/(?P<coach_id>\d+)/attendance/(?P<class_id>\d+)/session/(?P<session_id>\d+)$', views.class_session, name='class_session'),
    url(r'^coach/(?P<coach_id>\d+)/classes/$', views.classes_for_coach, name='classes_for_coach'),
    url(r'^coach/(?P<coach_id>\d+)/class/(?P<class_id>\d+)/$', views.class_overview, name='class_overview'),
    url(r'^coach/(?P<coach_id>\d+)/enroll/(?P<class_id>\d+)/$', views.enroll, name='enroll_student'),
    url(r'^coach/(?P<coach_id>\d+)/create_session/(?P<class_id>\d+)/$', views.create_session, name='create_session'),
    url(r'^login/$', views.login, name='login'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^logout/$', auth_views.logout,{'next_page': '/login/'}, name='auth_logout'),
    url(r'^signup/coaches/$', views.coach_signup, name='coach_signup'),
    url(r'^signup/coaches/verify/$', views.coach_verify, name='coach_verify'),
    url(r'^student/(?P<student_id>\d+)/$', views.student_profile, name='student_profile'),
    url(r'^student/(?P<student_id>\d+)/update/$', views.update_profile, name='update_profile'),
    url(r'^student/(?P<student_id>\d+)/approve_parent/$', views.approve_parent, name='approve_parent'),
    url(r'^student/(?P<student_id>\d+)/notes/$', views.student_notes, name='student_notes'),
    url(r'^student/(?P<student_id>\d+)/notes/leave/$', views.leave_note, name='leave_note'),
    url(r'^student/(?P<student_id>\d+)/goals/$', views.student_goals, name='student_goals'),
    url(r'^student/(?P<student_id>\d+)/goals/set/$', views.set_goal, name='set_goal'),
    url(r'^student/(?P<student_id>\d+)/goals/mark/(?P<goal_id>\d+)/$', views.mark_goal, name='mark_goal'),
    url(r'^student/(?P<student_id>\d+)/skills/$', views.student_skills, name='student_skills'),
    url(r'^student/(?P<student_id>\d+)/skill/(?P<skill_id>\d+)/subskills/$', views.skill_overview, name='skill_overview'),
    url(r'^student/(?P<student_id>\d+)/skill/(?P<skill_id>\d+)/subskills/mark/$', views.mark_skill, name='mark_skill'),
    url(r'^guardian/(?P<guardian_id>\d+)/add_relation/$', views.add_relation, name='add_relation'),
    url(r'^guardian/(?P<guardian_id>\d+)/home/$', views.parent_home, name='parent_home'),
    url(r'^coach/(?P<coach_id>\d+)/roster/(?P<class_id>\d+)/student/(?P<student_id>\d+)/remove/$', views.remove_student, name='remove_student'),

 ]

studentprogress/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from attendance import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('attendance.urls', namespace="attendance")),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/', TemplateView.as_view(template_name='attendance/student_profile.html')),
]

attendance/forms.py
from django.forms import ModelForm

from django import forms

from .models import Class, ClassSession, Coach, Student, AttendanceRecord, StudentProfile

from django.conf import settings

# class SignupForm(forms.Form):
# 	first_name = forms.CharField(max_length=30, label='First name')
# 	last_name = forms.CharField(max_length=30, label='Last name')
# 	email = forms.CharField(max_length=90, label='Email')
# 	number = forms.CharField(max_length=11, label='Phone')
# 	type_of_user = forms.ChoiceField(choices=(('student', 'student'), ('parent', 'parent'),))

# 	def signup(self, request, user):
# 		user.first_name = self.cleaned_data['first_name']
# 		user.last_name = self.cleaned_data['last_name']
# 		user.save()


# from allauth.account.forms import LoginForm as AllauthLoginForm

# class LoginForm(forms.Form):
    
#     def login(self, request, redirect_url=None):
        
#         response = super(LoginForm, self).login(request, redirect_url)
#         if request.user.is_authenticated():
#             redirect = settings.LOGIN_REDIRECT_URL.format(
#                 username=self.user.username)
#         else:
#             redirect = "/"
#         return HttpResponseRedirect(redirect)

attendance/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.core.urlresolvers import reverse, resolve
from django.http import HttpResponse, HttpResponseRedirect
from .models import Enrollment, Coach, Student, ClassSession, AttendanceRecord, Class, StudentProfile, StudentGoal, CoachNote, Skill, Subskill, StudentProgress, Relationship, StudentGuardian, Team, TeamMember, PassPhrase
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User, Group
from django.contrib.auth import login as login_user
from django.db import IntegrityError
from allauth.socialaccount.models import SocialToken
import collections
from decimal import Decimal

# Create your views here.
from datetime import datetime

from gitstat.git import git_zen

'''
	Decorators 

	group_check -- for now, any coach will have the ability to edit/add information to any coach's classes
'''

#Decorator method to help us check if the user is a coach
def group_check(user):
    return user.groups.filter(name__in=['coaches'])

#Helper function to let us know if this current user has the authorization to access this page 
def has_access(request, coach_id, class_id):
	if hasattr(request.user, 'coach'):
		can_access = False

		coach = Coach.objects.get(pk=coach_id)
		clas = Class.objects.get(pk=class_id)
		if request.user.coach == coach:
			can_access = True

		if request.user.coach.coach_id in TeamMember.objects.filter(team__head_coach=coach, team___class=clas).values_list('assistant_coach', flat=True):
			can_access = True

		return can_access
	else:
		return False

def home_page(request):
	return render(request, 'attendance/home_page.html', {})

''' 
Coaches methods 

'''

#View to render the roster for a coach and a class
@user_passes_test(group_check)
def class_roster(request, coach_id, class_id):
	if not has_access(request, coach_id, class_id):
		return render(request, 'attendance/unauthorized.html', {})

	coach = get_object_or_404(Coach, pk=coach_id)
	clas = get_object_or_404(Class, pk=class_id)
	query_set = Enrollment.objects.filter(coach=coach, _class=clas)

	return render(request, 'attendance/roster.html', {'roster': query_set, 'coach': coach, 'class': clas})

#View to render the roster and the edit attendance for a coach, a class, and a class session
@user_passes_test(group_check)
def class_session(request, coach_id, class_id, session_id):
	if not has_access(request, coach_id, class_id):
		return render(request, 'attendance/unauthorized.html', {})

	coach = get_object_or_404(Coach, pk=coach_id)
	clas = get_object_or_404(Class, pk=class_id)
	session = get_object_or_404(ClassSession, pk=session_id)
	query_set = Enrollment.objects.filter(coach=coach, _class=clas)

	#Get all of the students in alphabetical order for this particular session 
	student_records = AttendanceRecord.objects.filter(coach=coach, _class=clas, session=session).order_by('student__last_name')

	#For posts we'll update the data or create a new attendance record 
	if request.method == 'POST':

		#For all the enrollment objects in the query set
		for record in query_set:
			attended = False
			note = str(request.POST.get('note-' + str(record.student.student_id) ))
			if str(record.student.student_id) in request.POST.getlist('attended'):
				attended = True

			#Either update the existing record or create a new one
			try:
				#Get the old record and update it
				rec = AttendanceRecord.objects.get(coach=coach, session=session, student=record.student, _class=clas)
				rec.attended = attended
				if note != '':
					rec.note = note
				rec.save()
			except AttendanceRecord.DoesNotExist:
				#Create a new record then
				AttendanceRecord.objects.create(coach=coach, session=session, student=record.student, _class=clas, attended=attended, note=note)
		
		return HttpResponseRedirect(reverse('attendance:class_overview', args=(coach.coach_id, clas.class_id)))
	#Get requests will render a table full of attendance elements 
	else:
		isUpdate = False
		#If there are no previous attendance records, we'll notify the view that we shouldn't prepopulate the table 
		if len(student_records) != 0:
			isUpdate = True

		#Render the session template
		return render(request, 'attendance/session.html', {'roster': query_set, 'coach': coach, 'class': clas, 'session': session, 'isUpdate': isUpdate, 'old_records': student_records})


@user_passes_test(group_check)
def classes_for_coach(request, coach_id):
	coach = get_object_or_404(Coach, pk=coach_id)
	#This query will return a dictionary of all the unique classes this coach teaches
	classDicts = ClassSession.objects.filter(coach=coach).values('_class').distinct()
	teams = Team.objects.filter(head_coach=coach)
	classes = []
	for entry in teams:
		classes.append({'head_coach': entry.head_coach, 'class': entry._class})

	#For all the classes where our coach is an assistant, we'll go through and store those values too
	assistant_classes = []
	for entry in TeamMember.objects.filter(assistant_coach=coach):
		assist_dict = {}
		assist_dict['class'] = entry.team._class
		assist_dict['head_coach'] = entry.team.head_coach
		assistant_classes.append(assist_dict)


	return render(request, 'attendance/class_list.html', {'classes': classes, 'coach': coach, 'assistant_classes': assistant_classes})


#View to show an attendance overview for each student--showing how often they have come to the class
@user_passes_test(group_check)
def class_overview(request, class_id, coach_id):
	if not has_access(request, coach_id, class_id):
		return render(request, 'attendance/unauthorized.html', {})
	#Get the coach, class, and students
	coach = get_object_or_404(Coach, pk=coach_id)
	clas = get_object_or_404(Class, pk=class_id)
	sessions = ClassSession.objects.filter(coach=coach, _class=clas).order_by('class_date')
	enrollments = Enrollment.objects.filter(coach=coach, _class=clas).order_by('student__last_name')

	students_in_class = []
	student_attendance_records = []

	#Parse the students in the class
	for record in enrollments:
		students_in_class.append(record.student)
	
	#For each session, find the attendance record 
	for session in sessions:

		#A session dict will look like {'session': ClassSession, 'records': [{'note': 'Missed', 'attended': '-'}, {'note': '', 'attended': 'x'}, {'note': 'Hodor', 'attended': '-'}'}
		sessionDict = {}

		sessionDict['session'] = session
		students_records = []
		for student in students_in_class:
			student_record_dict = {}
			ar = AttendanceRecord.objects.filter(coach=coach, _class=clas, student=student, session=session)
			#If there is no record, then we'll populate the dictionary with a temporary value
			if len(ar) == 0:
				student_record_dict['attended'] = '/'
				student_record_dict['note'] = ''
			else:
				#Otherwise, store the attended/note from the AttendanceRecord
				if ar[0].attended:
					student_record_dict['attended'] = 'x'
				else:
					student_record_dict['attended'] = '-'
				student_record_dict['note'] = ar[0].note
			students_records.append(student_record_dict)

		#Records will be an array 
		sessionDict['records'] = students_records
		student_attendance_records.append(sessionDict)

	return render(request, 'attendance/overview.html', {'coach': coach, 'class': clas,  'sessions':sessions, 'records': student_attendance_records, 'students': students_in_class})



''' user auth '''

#For a signup request
def signup(request):

	#If it's a post then we'll authenticate and store the data entered
	if request.method == 'POST':
		username = request.POST['username']
		email = request.POST['email']
		password = request.POST['password']
		first_name = request.POST['first_name']
		last_name = request.POST['last_name']

		try:

			#Create a user object for these fields
			user = User.objects.create_user(username, email, password)
			user.first_name = first_name
			user.last_name = last_name
			user.save()
			user = authenticate(username=username, password=password)
			login_user(request, user)
		except IntegrityError as e:
			return render(request, 'attendance/signup.html', {'duplicate_key': True, 'first_name': first_name, 'last_name':last_name, 'email': email, 
				'username': '' })

		#Now we need to know which type of user we are registering
		type_of_user = request.POST['type']

		#For students we will need to create a profile 
		if type_of_user == 'Student':
			profile = StudentProfile.objects.create(email=email, user=user)
			student = Student.objects.create(first_name=first_name, last_name=last_name, profile=profile)
			
			return redirect('attendance:student_profile', student_id=student.student_id)
			#return render(request, 'attendance/student_profile.html', {'student': student, 'profile': profile, 'can_edit': True, 'should_update': True})
		#For parents we have to make sure they approved to view their student's information
		elif type_of_user == 'Parent':
			#Create a new guardian object here
			guardian = StudentGuardian.objects.create(name=first_name + ' ' + last_name, user=user)
			return redirect('attendance:add_relation', guardian_id=guardian.guardian_id)

	#Get requests will return the signup html page
	else:
		return render(request, 'attendance/signup.html', {'duplicate_key': False, 'first_name': 
			'', 'last_name':'', 'email': '', 
				'username': '' })


#View for a standard login page
def login(request):
	#post will authenticate a user 
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		#If the user was authenticated, then we'll log them in
		if user is not None:
			if user.is_active:
				login_user(request, user)
				#Take them to their profile if they have one (aka a student, not a parent)
				if hasattr(user, 'studentprofile'):
					student = Student.objects.get(profile=user.studentprofile)

					return redirect('attendance:student_profile', student_id=student.student_id)

attendance/templates/attendance/class_list.html
{% extends 'attendance/base.html' %}

{% block content %}   

{% for group in user.groups.all %}
    {% if group.name == 'coaches' %}
        <div class="pure-menu pure-menu-horizontal">
            
            <ul class="pure-menu-list">
                <li class="pure-menu-item"><a href="{% url 'attendance:classes_for_coach' coach_id=user.coach.coach_id %}" class="pure-menu-link"><i class="fa fa-home fa-2x" aria-hidden="true"></i>  home</a></li>

                <li class="pure-menu-item"><a href="{% url 'attendance:coach_dashboard' %}" class="pure-menu-link"><i class="fa fa-dashboard fa-2x" aria-hidden="true"></i>  dashboard</a></li>

                <li class="pure-menu-item">
                    <a href="{% url 'attendance:auth_logout' %}" class="pure-menu-link"><i class="fa fa-sign-out fa-2x" aria-hidden="true"></i> sign out</a>
                </li>

            </ul>
        </div>
    {% endif %}
{% endfor %} 

    <div class="table-data pure-menu pure-menu-horizontal">

        <h1> {{coach}}</a></h1>

        <table class="pure-table center pure-table-horizontal">
            <thead>
                <tr>
                    <th>Role</th>
                    <th>Class</th>
                </tr>
            </thead>

            <tbody>

                {% for entry_dict in classes %}

                <tr>
                    <td> Lead </td>
                    <td> <a href="{% url 'attendance:class_roster' class_id=entry_dict.class.class_id coach_id=entry_dict.head_coach.coach_id %}"> {{ entry_dict.class }} </a> </td>
                    
                </tr>

                {% endfor %}

                {% for entry in assistant_classes %}

                <tr>
                    <td> Assistant </td>
                    <td> <a href="{% url 'attendance:class_roster' class_id=entry.class.class_id coach_id=entry.head_coach.coach_id %}"> {{ entry.class }} </a> </td>
                    
                </tr>

                {% endfor %}



            </tbody>

    </table>



    </div>


{% endblock %}

attendance/templates/attendance/coach_portal.html
{% extends 'attendance/base.html' %}

{% block content %}   

<div id="outter-signup-form">
    <div id="inner-signup-form">

    <br> 
    <br> 

    
    <form class="pure-form pure-form-stacked" action="" method="post">
            {% csrf_token %}
    <fieldset>
        <legend class="legend"><h1> Create a Coach Account </h1></legend>

        {% load socialaccount %}

        <p><i class="fa fa-github fa-4x"></i><a href="{% url 'attendance:coach_verify'%}?next={% provider_login_url "github" %}"> <big>Coaches--Sign up with Github</big></a></p>

        <label for="fname">First name</label>
        <input name="first_name" id="fname" type="text" placeholder="John" value="{{first_name}}" required>

        <label for="fname">Last name</label>
        <input name="last_name" id="lname" type="text" placeholder="Doe" value="{{last_name}}" required>

        <label for="email">Email</label>
        <input name="email" id="email" type="email" placeholder="Email" value="{{email}}" required>

        <br> 
        <br>

        <label for="username">Username</label>
        <input name="username" id="username" type="text" placeholder="Username" value="{{username}}" required>

        <label for="password">Password</label>
        <input name="password" id="password" type="password" placeholder="Password" required>

        <label for="coach_phrase">Coach key</label>
        <input name="coach_phrase" id="coach_phrase" type="password" placeholder="Ask Nick" required>

        <br>

        <button type="submit" class="pure-button pure-button-primary">Sign up</button>
    </fieldset>
    </form>    

        {% if duplicate_key %}

                <div class="error">Username taken</div>

        {% endif %}

        {% if wrong_phrase %}

                <div class="error">Wrong secret phrase. Contact Nick Such</div>

        {% endif %}

    </div>
</div>






{% endblock %}

attendance/templates/attendance/roster.html
{% extends 'attendance/base.html' %}

{% block content %}   


{% for group in user.groups.all %}
    {% if group.name == 'coaches' %}
        <div class="pure-menu pure-menu-horizontal">
            
            <ul class="pure-menu-list">
                <li class="pure-menu-item"><a href="{% url 'attendance:classes_for_coach' coach_id=user.coach.coach_id %}" class="pure-menu-link"><i class="fa fa-home fa-2x" aria-hidden="true"></i>  home</a></li>

                <li class="pure-menu-item"><a href="{% url 'attendance:coach_dashboard' %}" class="pure-menu-link"><i class="fa fa-dashboard fa-2x" aria-hidden="true"></i>  dashboard</a></li>

                <li class="pure-menu-item">
                    <a href="{% url 'attendance:auth_logout' %}" class="pure-menu-link"><i class="fa fa-sign-out fa-2x" aria-hidden="true"></i> sign out</a>
                </li>

            </ul>
        </div>
    {% endif %}
{% endfor %} 

    <div class="table-data pure-menu pure-menu-horizontal">

        <h1> {{class}} with <a href="{% url 'attendance:classes_for_coach' coach_id=coach.coach_id%}">{{coach}}</a></h1>

        <table class="pure-table center pure-table-horizontal">
            <thead>
                <tr>
                    <th>Student #</th>
                    <th>First name</th>
                    <th>Last name</th>
                    <th> Email </th>
                    <th> Profile </th>
                    <th> Remove </th>
                </tr>
            </thead>

            <tbody>

                {% for record in roster %}

                <tr>
                    <td> {{ forloop.counter }}</td>
                    <td> {{ record.student.first_name }} </td>
                    <td> {{ record.student.last_name }}  </td>
                    <td> {{ record.student.profile.email }} </td>
                    <td> <a href="{% url 'attendance:student_profile' student_id=record.student_id %}"> Profile </a> </td> 
                    <td> <a href="{% url 'attendance:remove_student' coach_id=coach.coach_id  class_id=class.class_id student_id=record.student_id %}" class="pure-menu-link"><i class="fa fa-trash-o" aria-hidden="true"></i>  </a> </td>
                </tr>

                {% endfor %}

            </tbody>

    </table>

    <ul class="pure-menu-list">
        <li class="pure-menu-item"><a href="{% url 'attendance:class_overview' coach_id=coach.coach_id class_id=class.class_id%}" class="pure-menu-link white">Take attendance</a></li>
        <li class="pure-menu-item"><a href="{% url 'attendance:enroll_student' coach_id=coach.coach_id class_id=class.class_id%}" class="pure-menu-link white">Enroll a student</a></li>
        <li class="pure-menu-item"><a href="{% url 'attendance:create_session' coach_id=coach.coach_id class_id=class.class_id%}" class="pure-menu-link white">Create class session</a></li>
    </ul>


    </div>


{% endblock %}

attendance/templates/attendance/student_profile.html
{% extends 'attendance/profile-base.html' %}

{% block content %} 



<section class="dashboard">

    {% for group in user.groups.all %}
        {% if group.name == 'coaches' %}
            <div class="pure-menu pure-menu-horizontal">
                <p class="pure-menu-heading">{{user.coach}}</p>
                <ul class="pure-menu-list">
                    <li class="pure-menu-item"><a href="{% url 'attendance:classes_for_coach' coach_id=user.coach.coach_id %}" class="pure-menu-link"><i class="fa fa-home fa-2x" aria-hidden="true"></i>  home</a></li>                  
                </ul>
            </div>
        {% endif %}

    {% endfor %} 


    {% if request.user.studentprofile.student.student_id == student.student_id %}
        <div class="pure-menu pure-menu-horizontal">
            <p class="pure-menu-heading">My profile</p>
            <ul class="pure-menu-list">
                <li class="pure-menu-item"><a href="{% url 'attendance:approve_parent' student_id=student.student_id %}" class="pure-menu-link"><i class="fa fa-users fa-2x" aria-hidden="true"></i> parents {% if new_relations > 0 %} ({{new_relations}} pending) {% endif %}</a></li>
                <li class="pure-menu-item"><a href="{% url 'attendance:update_profile' student_id=student.student_id %}" class="pure-menu-link"><i class="fa fa-cog fa-2x" aria-hidden="true"></i> settings </a></li>

                <li class="pure-menu-item">
                    {%if student.profile.bio == '' or student.profile.phone == '' or student.profile.github_user_name == '' %}
                    <p> Update your information now! </p>
                    {% endif %}
                </li>
                <li class="pure-menu-item">
                    <a href="{% url 'attendance:auth_logout' %}" class="pure-menu-link"><i class="fa fa-sign-out fa-2x" aria-hidden="true"></i> sign out</a>
                </li>
            </ul>

        </div>

        
    {% endif %}


    <div class="pure-g">
        <div class="pure-u-1 dashboard-piece dashboard-piece-logo">

        <h2 class="title">
            {{student}}
        </h2>
        <div class="pure-g">
            <div class="pure-u-1-3"></div>
            <div class="pure-u-1-3">
                <div class="roundedImage img">&nbsp;</div>
            </div>
            <div class="pure-u-1-3"></div>
        </div>
        
        <h2 class="bio"> {{student.profile.bio}}</h2>

        <div class="pure-g">
        <div class="pure-u-1-3"><p><i class="fa fa-phone fa-1x" aria-hidden="true"></i> <a class="pure-menu-heading">{{student.profile.phone}}</a></p></div>
        <div class="pure-u-1-3"><p> <i class="fa fa-envelope-o fa-1x" aria-hidden="true"></i> <a class="pure-menu-link" href="mailto:{{student.profile.email}}">{{student.profile.email}}</a></p></div>
        <div class="pure-u-1-3"><p><i class="fa fa-github fa-1x" aria-hidden="true"></i>  <a class="pure-menu-link" href="http://github.com/{{student.profile.github_user_name}}"><big>{{student.profile.github_user_name}}</big></a></p></div>
        </div>

    </div>

    </div>

    <div class="pure-g">

        <div class="pure-u-1-3 dashboard-piece dashboard-piece-greenbg">
            <div class="dashboard-content">
                <h2><i class="fa fa-dashboard fa-4x"></i></h2>
                <p class="dashboard-metric"> <a class="dash-link" href="{% url 'attendance:student_goals' student_id=student.student_id %}"> Goals </a>

                    <div class="dashboard-metric">
                                        <p class="dashboard-metric"><span class="light">{{goals_met}}/{{goals_set}} complete</span></p>
                    </div>

                </p>
            </div>
        </div>
        <div class="pure-u-1-3 dashboard-piece dashboard-piece-orangebg">

            <div class="dashboard-content">
                    <h2><i class="fa fa-code fa-4x"></i></h2><p class="dashboard-metric"> <a class="dash-link" href="{% url 'attendance:student_skills' student_id=student.student_id %}"> Skills </a></p>

                    <div class="dashboard-metric">

                                        <div class="light bar-horizontal">
                                               <div class="bar-horizontal-bar" style="width:{{percent_complete}}%">
                                                   {{percent_complete}}% complete
                                               </div>
                                        </div>
                    </div>
            </div>
            
        </div>
        <div class="pure-u-1-3 dashboard-piece dashboard-piece-bluebg">
            <div class="dashboard-content">
                    <h2><i class="fa fa-sticky-note-o fa-4x"></i></h2><p class="dashboard-metric"> <a class="dash-link" href="{% url 'attendance:student_notes' student_id=student.student_id %}"> Inbox </a> </p>

                    <div class="dashboard-metric">
                                        <p class="dashboard-metric"><span class="light">{{notes}} notes</span></p>
                    </div>
            </div>
        </div>

    </div>

    <div class="pure-g">
        <div class="pure-u-1-2 dashboard-piece dashboard-piece-redbg">
            <div class="dashboard-content">
                    <h2><i class="fa fa-calendar-o fa-4x"></i></h2><p class="dashboard-metric"> Upcoming </p>

                    <div class="pure-g">
                        <div class="pure-u-1-3">
                        </div>


                        <div class="pure-u-1-3">

                        {% if num_upcoming != 0 %}
                            <table class="pure-table pure-table-bordered">
                                <thead>
                                    <tr>
                                        <th>Class</th>
                                        <th>Date</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    {% for dict in upcoming %}
                                        {% for session in dict.sessions %}

                                            <tr>
                                                <td>{{dict.class}}</td>
                                                <td>{{session.class_date.month}}/{{session.class_date.day}}/{{session.class_date.year}} {{session.class_date.time}}</td>
                                            </tr>
                                        {%endfor%}
                                    {% endfor %}
                                </tbody>
                            </table>
                        {% else %}
                            <div class="dashboard-metric">
                                                <p class="dashboard-metric"><span class="light">0 events</span></p>
                            </div>

                        {% endif %}
                        </div>

                        <div class="pure-u-1-3">
                        </div>
                    
                    </div>
            </div>
        </div>

        <div class="pure-u-1-2 dashboard-piece dashboard-piece-blackbg">
            <div class="dashboard-content">
                <h2><i class="fa fa-github fa-4x"></i></h2>
                <p class="dashboard-metric">
                    Github feed:

                    <div id="feed">
                                        
                    </div>
                </p>
            </div>
        </div>
    </div>
    
    
</section>

<div class="profile">

    <style>
        a:link.pure-menu-link  {color:#F6AE2D; background-color:transparent; text-decoration:none}
        a:visited.pure-menu-link {color:#F6AE2D; background-color:transparent; text-decoration:none}
        a:hover.pure-menu-link   {color:#F26419; background-color:transparent; text-decoration:underline}
        a:active.pure-menu-link  {color:#F6AE2D; background-color:transparent; text-decoration:underline}

        a:link.dash-link  {color:white; background-color:transparent; text-decoration:none}
        a:visited.dash-link {color:white; background-color:transparent; text-decoration:none}
        a:hover.dash-link   {color:white; background-color:transparent; text-decoration:underline}
        a:active.dash-link  {color:white; background-color:transparent; text-decoration:underline}

        .roundedImage {
            background: url({{student.profile.profile_img_url}});
            background-repeat: no-repeat;
            background-size: cover;
            
            overflow:hidden;
            -webkit-border-radius:50px;
            -moz-border-radius:50px;
            border-radius:15px;
            width:150px;
            height:150px;
        }


    </style>
    
</div>

            {% load staticfiles %}
            <link rel="stylesheet" href="{% static 'activity-feed/octicons.min.css' %}">
            <link rel="stylesheet" href="{% static 'activity-feed/github-activity-0.1.4.min.css' %}">

            <script type="text/javascript" src="{% static 'activity-feed/mustache.min.js' %}"></script>
            <script type="text/javascript" src="{% static 'activity-feed/github-activity-0.1.4.min.js' %}"></script>
            <script>
                GitHubActivity.feed({ username: '{{github_username}}', selector: '#feed', limit:5});
            </script>
            <style type="text/css">

                    #feed{
                        width: 95%;
                        height: auto;
                        margin: 0 auto;
                        color: black;
                    }
            </style>



{% endblock %}

attendance/templates/attendance/unauthorized.html
{% extends 'attendance/profile-base.html' %}

{% block content %} 

<div align="center">

    <h1> Unauthorized </h1>

    {%if error_message%}
        <h2> {{error_message}} </h2>
    {%else%}
        <h2> You don't have access to this page </h2>

    {%endif%}
    
    <input type=button value="Previous Page" onClick="javascript:history.go(-1);">



</div>



{% endblock %}